Hero banner rover
WildCodeSchool/tlse0321-js-p2-wheels-on-mars pull request #25
Opened 2021-04-21 15:14 UTC by davidbourrel

2021-04-21 15:24 UTC, SebastienFrancois approved these changes
Ok pour moi

2021-04-22 12:44 UTC, Froyj commented on src/pages/curiosity/Curiosity.jsx
>    };
A priori ce son des constantes, idealement stocker ces infos dans un fichiers séparé dans un dossier 'constants' et les importer la ou vous en avez besoin (les noms de variables s'ecrivent en majuscules & _ ==> ex : OPPORTUNITY_ROVER_3D_URL)

2021-04-22 12:44 UTC, Froyj commented on src/pages/opportunity/Opportunity.jsx
>    };
pareil

2021-04-22 12:44 UTC, Froyj commented on src/pages/perseverance/Perseverance.jsx
>    };
pareil

2021-04-22 12:45 UTC, Froyj requested changes
Au moins effacer le code mort

2021-04-22 15:08 UTC, davidbourrel commented on src/pages/curiosity/Curiosity.jsx
>    };
Ok merci ! j'ai tout mis dans le dossier "contants" et j'ai importé ce dont j'avais besoin sur chaque page. Normalement c'est bon pour moi.

2021-04-22 15:08 UTC, davidbourrel commented
> 
> 
> Au moins effacer le code mort

Done ! Thanks

2021-04-23 06:20 UTC, Froyj approved these changes

2021-04-23 07:06 UTC, merged